### ISSUE TITLE
Wrong cursor offset on Windows.

### ISSUE THREAD

**Issue by ChrisHines** [alvarolm/GoRename#4]
This issue is probably similar to the one I fixed in GoGuru in this commit: https://github.com/alvarolm/GoGuru/pull/6/commits/76f09c246b050136c3a7dc84499828446e67c16c.

**Comment by alvarolm** [comment]
https://github.com/alvarolm/GoRename/commit/dc1207271654428ca9140706eb321605d1cdbbc9 , thanks Chris ;)

**Comment by ChrisHines** [comment]
It works correctly now. Thanks.
